name: GitHub Pages

on:
  push:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install depedencies
      run: cargo install wasm-pack

    - name: Build WASM
      working-directory: wasm
      run: wasm-pack build --target web

    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      path: wasm/pkg wasm/index.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy Pages
      uses: actions/deploy-pages@v4
