name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install depedencies
      run: cargo install wasm-pack

    - name: Build WASM
      working-directory: wasm
      run: wasm-pack build --target web

    - name: Publish
      run: |
        git clone $(git remote get-url origin) --branch gh-pages pages
        git -C pages rm '*'
        cp -R wasm/pkg wasm/index.html pages
        git -C pages add . --force
        git -C pages config user.name github-actions[bot]
        git -C pages config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git -C pages commit -m "Publish commit $(git rev-parse HEAD --short)"
        git -C pages push
